# 服务器地址
url = "http://localhost:2536"
# 服务器端口
port = 2536
# 服务器缺省跳转地址
redirect = "https://github.com/Alex6357/yuzai"
# 服务器鉴权
authToken = ""
[https]
# 是否启用 https 服务器
enabled = false
# https 服务器地址
url = "https://localhost:2537"
# https 服务器端口
port = 2537
# https 服务器证书
key = "config/localhost.key"
cert = "config/localhost.crt"
