# TODO 好好写
[default]
# 群聊中所有指令操作冷却时间，单位毫秒,0则无限制
groupCD = 500
# 群聊中个人操作冷却时间，单位毫秒
singleCD = 2000
# 是否只仅关注主动提及Bot的消息 0-否 1-是 2-非主人
onlyReplyAt = 0
# 开启后则只回复提及Bot的消息及特定前缀的消息
botAlias = ["云崽", "云宝"]
# 是否限制添加消息 0-所有群员 1-群管理员 2-主人
addLimit = 0
# 是否允许私聊添加
addPrivate = 1
# 是否回复触发消息
addReply = 1
# 是否提及触发用户
addAt = 0
# 是否撤回回复消息
addRecall = 60

# 只启用功能，配置后只有该功能才响应
enable = [""]
# 禁用功能，功能名称,例如：十连、角色查询、体力查询、用户绑定、抽卡记录、添加表情、欢迎新人、退群通知
disable = ["禁用示例", "支持多个"]

# 群单独设置
[123456]
groupCD = 500
singleCD = 2000

# Bot单独设置
[114514.default]
onlyReplyAt = 1
botAlias = ["臭崽", "臭宝"]

# [Bot:群]单独设置
[114514.123456]
enable = [""]
disable = [""]
