# 插件加载超时
pluginLoadTimeout = 60
# 监听文件变化
fileWatch = true
# 上线推送通知的冷却时间
onlineMsgExp = 1440
# 文件保存时间
fileToUrlTime = 1
# 文件访问次数
fileToUrlTimes = -1
# 消息类型统计
msgTypeCount = false
# 以/开头转为#
slashToHash = true
# 米游社接口代理地址，国际服用
# proxyAddress:

[schedule]
# 自动更新时间
updateTime = 1440
# 自动重启时间
restartTime = 0
# 定时更新cron表达式
updateCron = ""
# 定时重启cron表达式
restartCron = ""
# 定时关机cron表达式
stopCron = ""
# 定时开机cron表达式
startCron = ""

[log]
# 日志等级 trace,debug,info,warn,fatal,mark,error,off
level = "info"
# 单条日志长度
length = 10000
# 对象日志格式
object = true
# 日志ID对齐
align = "  Yuzai  "
